# Copyright (2024) Beijing Volcano Engine Technology Ltd.
account:
  ak: ""  # Volcengine account ak
  sk: ""  # Volcengine account sk

  region: ""
  topHost: open.volcengineapi.com
  vpcID: ""  # Volcengine VPC ID
  subnetIDs: []   # The subnets of the vpc, used to allocate ip for clb
  clusterID: ""  # The unique identifier
  projectName: default  # The name of project, default value is default

service:
  enabled: true
  type: ClusterIP
  metrics:
    port: 8081
    portName: metrics
  annotations: {}

controller:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 500Mi
  image:
    registry:  open-registry-cn-beijing.cr.volces.com/vke
    name: cloud-controller-manager
    tag: v1.35.0-public
  affinity: {}
  labels: {}
  componentSetting:
    logLevel: 2  #
    concurrentServiceSyncs: 1
    loadBalancerClass: volcengine.com/clb  # The service.spec.loadBalancerClass, default is volcengine.com/clb
    watchServiceWithoutClass: false  # Whether to reconcile the Service without the loadBalancerClass field

    authenticationMode: inCluster  # inCluster or useKubeconfig
    serviceAccountName: ""