apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ template "common.names.fullname" . }}
stringData:
  config.json: |
    {
      "access_key": {{ .Values.account.ak | quote }},
      "secret_key": {{ .Values.account.sk | quote }},
      "account_id": {{ .Values.account.accountID | quote }},
      "region": {{ .Values.account.region | quote }},
      "top_host": {{ .Values.account.topHost | quote }},
      "vpc_id": {{ .Values.account.vpcID | quote }},
      "subnet_id": {{ .Values.account.subnetID | quote }},
      "subnet_ids": {{ .Values.account.subnetIDs | toJson }},
      "network_model": {{ .Values.account.networkModel | quote }},
      "vke_service_name": {{ .Values.account.serviceName | quote }},
      "cluster_id": {{ .Values.account.clusterID | quote }}
    }
type: Opaque
