# Copyright (2024) Beijing Volcano Engine Technology Ltd.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
stringData:
  config.json: |
    {
      "access_key": {{ .Values.account.ak | quote }},
      "secret_key": {{ .Values.account.sk | quote }},
      "region": {{ .Values.account.region | quote }},
      "top_host": {{ .Values.account.topHost | quote }},
      "vpc_id": {{ .Values.account.vpcID | quote }},
      "subnet_ids": {{ .Values.account.subnetIDs | toJson }},
      "cluster_id": {{ .Values.account.clusterID | quote }},
      "project_name": {{ .Values.account.projectName | quote }}
    }
type: Opaque
