# Copyright (2024) Beijing Volcano Engine Technology Ltd.
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
{{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | indent 4}}
{{- end}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.metrics.portName }}
      port: {{ .Values.service.metrics.port }}
      protocol: TCP
      targetPort: {{ .Values.service.metrics.portName }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end}}